// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package app

import (
	"database/sql"
)

type Line struct {
	ID   int64
	Name sql.NullString
	Type sql.NullString
	NID  sql.NullInt64
}

type Node struct {
	ID     int64
	Name   sql.NullString
	NodeID sql.NullInt64
	NID    sql.NullInt64
}
